### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Philomath88** [bayeru/chat-to-your-database#1]
First of all, thanks for the project!

Am thinking of doing the same with a noSQL database - do you have any thoughts on that? 

Also, would recommend to add a base .env file with empty OPENAI_API_KEY

**Comment by bayeru** [comment]
Thanks, I just added a sample .env file. Regarding NoSQL databases, I used the SQL agent toolkit from LangChain, afaik it doesn't have a NoSQL toolkit, you can try to implement it yourself by following the LangChain documentation here https://js.langchain.com/
